#!/bin/sh
which xclip &> /dev/null
if [ ! $? -eq 0 ]; then
  echo "xclip not found"
  exit 1
fi

if test -n "$1"; then
  if [ -f $1 ]; then
    cat $@ | xclip -i -selection clipboard
  fi
elif test ! -t 0; then
  xclip -i -selection clipboard
else
  echo "No data provided..."
  exit 1
fi
