#!/bin/sh

which xclip &> /dev/null
if [ ! $? -eq 0 ]; then
  XCLIP_FOUND=0
else
  XCLIP_FOUND=1
fi
which wl-copy &> /dev/null
if [ ! $? -eq 0 ]; then
  WLCOPY_FOUND=0
else
  WLCOPY_FOUND=1
fi

if [[ ${WLCOPY_FOUND} -eq 0 && ${XCLIP_FOUND} -eq 0 ]]; then
  echo 'no copy utility found'
  exit 1
fi

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  if [[ ${WLCOPY_FOUND} -eq 0 ]]; then
    echo 'wl-copy utility found'
    exit 1
  fi
  COPY_CMD=wl-copy
elif [ "$XDG_SESSION_TYPE" = "x11" ]; then
  if [[ ${XCLIP_FOUND} -eq 0 ]]; then
    echo 'xclip utility found'
    exit 1
  fi
  COPY_CMD="xclip -i -selection clipboard"
else
  echo "Unknown or headless session (Type: $XDG_SESSION_TYPE)"
  exit 1
fi


if test -n "$1"; then
  if [ -f $1 ]; then
    cat $@ | ${COPY_CMD}
  fi
elif test ! -t 0; then
  ${COPY_CMD}
else
  echo "No data provided..."
  exit 1
fi
